#!/bin/bash

# trace_name '.' trace_opt '.' cluster_method '.c' num2str(num_cluster) '.' warp_method '.' warp_opt '.'  rank_opt '.elem' num2str(elem_frac) '.lr' num2str(loss_rate) '.' elem_mode '.' loss_mode '.' num2str(burst_size) '.' init_esti_method '.' final_esti_method '.s' num2str(seed) '.txt'
# trace_name, trace_opt, ...
# rank_opt, ...
# elem_frac, loss_rate, elem_mode, loss_mode, burst_size, ...
# init_esti_method, final_esti_method, ...
# num_cluster, cluster_method, ...
# warp_method, warp_opt, ...
# seed
matlab -r "out_file = ['/u/yichao/warp/condor_data/task_dtw/condor/do_missing_exp/TRACE_NAME.TRACE_OPT.RANK_OPT.elemELEM_FRAC.lrLOSS_RATE.ELEM_MODE.LOSS_MODE.BURST_SIZE.INIT_ESTI_METHOD.FINAL_ESTI_METHOD.CLUST_METHOD.cNUM_CLUST.WARP_METHOD.WARP_OPT.EVAL_OPT.sSEED.txt']; if(exist(out_file)), exit; end; do_missing_exp('TRACE_NAME', 'TRACE_OPT', 'RANK_OPT', ELEM_FRAC, LOSS_RATE, 'ELEM_MODE', 'LOSS_MODE', BURST_SIZE, 'INIT_ESTI_METHOD', 'FINAL_ESTI_METHOD', 'CLUST_METHOD', NUM_CLUST, 'WARP_METHOD', 'WARP_OPT', 'EVAL_OPT', SEED); exit;"
