#!/bin/bash

# trace_name, trace_opt, drop_opt, ...
# sync_opt, cluster_opt, eval_opt, ...
# init_esti_method, final_esti_method, ...
# seed
matlab -r "out_file = ['/u/yichao/warp/condor_data/task_miss/condor/do_missing_exp/TRACE_NAME.TRACE_OPT.DROP_OPT.SYNC_OPT.CLUSTER_OPT.EVAL_OPT.INIT_ESTI_METHOD.FINAL_ESTI_METHOD.SEED.txt']; if(exist(out_file)), exit; end; do_missing_exp('TRACE_NAME', 'TRACE_OPT', 'DROP_OPT', 'SYNC_OPT', 'CLUSTER_OPT', 'EVAL_OPT', 'INIT_ESTI_METHOD', 'FINAL_ESTI_METHOD', SEED); exit;"
